language: android
os: linux
dist: xenial

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6

env:
  global:
    - APP_PATH="$TRAVIS_BUILD_DIR/grpcchat-client/app/build/outputs/apk/release/app-release.apk"
    - TEST_APP_PATH="$TRAVIS_BUILD_DIR/grpcchat-client/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"

script: 
  - ./grpcchat-client/gradlew assembleRelease
  - ./grpcchat-client/gradlew assembleDebug
  - ./grpcchat-client/gradlew test
