# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messenger_pb2 as messenger__pb2


class MessengerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sayMessage = channel.unary_unary(
                '/Messenger/sayMessage',
                request_serializer=messenger__pb2.MessengerMessage.SerializeToString,
                response_deserializer=messenger__pb2.MessengerReply.FromString,
                )


class MessengerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sayMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessengerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sayMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.sayMessage,
                    request_deserializer=messenger__pb2.MessengerMessage.FromString,
                    response_serializer=messenger__pb2.MessengerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Messenger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Messenger(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sayMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Messenger/sayMessage',
            messenger__pb2.MessengerMessage.SerializeToString,
            messenger__pb2.MessengerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
