# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messenger.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fmessenger.proto\"#\n\x10MessengerMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"$\n\x14MessengerNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"8\n\x15MessengerNameResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tconnected\x18\x02 \x01(\x08\x32\xc2\x01\n\tMessenger\x12\'\n\ngetMessage\x12\x11.MessengerMessage\x1a\x06.Empty\x12*\n\x0bsendMessage\x12\x06.Empty\x1a\x11.MessengerMessage0\x01\x12?\n\x0estartMessaging\x12\x15.MessengerNameRequest\x1a\x16.MessengerNameResponse\x12\x1f\n\rstopMessaging\x12\x06.Empty\x1a\x06.Emptyb\x06proto3'
)




_MESSENGERMESSAGE = _descriptor.Descriptor(
  name='MessengerMessage',
  full_name='MessengerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='MessengerMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=54,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=63,
)


_MESSENGERNAMEREQUEST = _descriptor.Descriptor(
  name='MessengerNameRequest',
  full_name='MessengerNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MessengerNameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=101,
)


_MESSENGERNAMERESPONSE = _descriptor.Descriptor(
  name='MessengerNameResponse',
  full_name='MessengerNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MessengerNameResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connected', full_name='MessengerNameResponse.connected', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['MessengerMessage'] = _MESSENGERMESSAGE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['MessengerNameRequest'] = _MESSENGERNAMEREQUEST
DESCRIPTOR.message_types_by_name['MessengerNameResponse'] = _MESSENGERNAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessengerMessage = _reflection.GeneratedProtocolMessageType('MessengerMessage', (_message.Message,), {
  'DESCRIPTOR' : _MESSENGERMESSAGE,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:MessengerMessage)
  })
_sym_db.RegisterMessage(MessengerMessage)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

MessengerNameRequest = _reflection.GeneratedProtocolMessageType('MessengerNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _MESSENGERNAMEREQUEST,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:MessengerNameRequest)
  })
_sym_db.RegisterMessage(MessengerNameRequest)

MessengerNameResponse = _reflection.GeneratedProtocolMessageType('MessengerNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSENGERNAMERESPONSE,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:MessengerNameResponse)
  })
_sym_db.RegisterMessage(MessengerNameResponse)



_MESSENGER = _descriptor.ServiceDescriptor(
  name='Messenger',
  full_name='Messenger',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=162,
  serialized_end=356,
  methods=[
  _descriptor.MethodDescriptor(
    name='getMessage',
    full_name='Messenger.getMessage',
    index=0,
    containing_service=None,
    input_type=_MESSENGERMESSAGE,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sendMessage',
    full_name='Messenger.sendMessage',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MESSENGERMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='startMessaging',
    full_name='Messenger.startMessaging',
    index=2,
    containing_service=None,
    input_type=_MESSENGERNAMEREQUEST,
    output_type=_MESSENGERNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='stopMessaging',
    full_name='Messenger.stopMessaging',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSENGER)

DESCRIPTOR.services_by_name['Messenger'] = _MESSENGER

# @@protoc_insertion_point(module_scope)
