# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messenger.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fmessenger.proto\"3\n\x10MessengerMessage\x12\x0e\n\x06whoami\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x10\n\x0eMessengerReply2=\n\tMessenger\x12\x30\n\nsayMessage\x12\x11.MessengerMessage\x1a\x0f.MessengerReplyb\x06proto3'
)




_MESSENGERMESSAGE = _descriptor.Descriptor(
  name='MessengerMessage',
  full_name='MessengerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='whoami', full_name='MessengerMessage.whoami', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='MessengerMessage.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=70,
)


_MESSENGERREPLY = _descriptor.Descriptor(
  name='MessengerReply',
  full_name='MessengerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['MessengerMessage'] = _MESSENGERMESSAGE
DESCRIPTOR.message_types_by_name['MessengerReply'] = _MESSENGERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessengerMessage = _reflection.GeneratedProtocolMessageType('MessengerMessage', (_message.Message,), {
  'DESCRIPTOR' : _MESSENGERMESSAGE,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:MessengerMessage)
  })
_sym_db.RegisterMessage(MessengerMessage)

MessengerReply = _reflection.GeneratedProtocolMessageType('MessengerReply', (_message.Message,), {
  'DESCRIPTOR' : _MESSENGERREPLY,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:MessengerReply)
  })
_sym_db.RegisterMessage(MessengerReply)



_MESSENGER = _descriptor.ServiceDescriptor(
  name='Messenger',
  full_name='Messenger',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=90,
  serialized_end=151,
  methods=[
  _descriptor.MethodDescriptor(
    name='sayMessage',
    full_name='Messenger.sayMessage',
    index=0,
    containing_service=None,
    input_type=_MESSENGERMESSAGE,
    output_type=_MESSENGERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSENGER)

DESCRIPTOR.services_by_name['Messenger'] = _MESSENGER

# @@protoc_insertion_point(module_scope)
