# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messenger_pb2 as messenger__pb2


class MessengerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getMessage = channel.unary_unary(
                '/Messenger/getMessage',
                request_serializer=messenger__pb2.MessengerMessage.SerializeToString,
                response_deserializer=messenger__pb2.Empty.FromString,
                )
        self.sendMessage = channel.unary_stream(
                '/Messenger/sendMessage',
                request_serializer=messenger__pb2.Empty.SerializeToString,
                response_deserializer=messenger__pb2.MessengerMessage.FromString,
                )
        self.startMessaging = channel.unary_unary(
                '/Messenger/startMessaging',
                request_serializer=messenger__pb2.MessengerNameRequest.SerializeToString,
                response_deserializer=messenger__pb2.MessengerNameResponse.FromString,
                )
        self.stopMessaging = channel.unary_unary(
                '/Messenger/stopMessaging',
                request_serializer=messenger__pb2.Empty.SerializeToString,
                response_deserializer=messenger__pb2.Empty.FromString,
                )


class MessengerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startMessaging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopMessaging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessengerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.getMessage,
                    request_deserializer=messenger__pb2.MessengerMessage.FromString,
                    response_serializer=messenger__pb2.Empty.SerializeToString,
            ),
            'sendMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.sendMessage,
                    request_deserializer=messenger__pb2.Empty.FromString,
                    response_serializer=messenger__pb2.MessengerMessage.SerializeToString,
            ),
            'startMessaging': grpc.unary_unary_rpc_method_handler(
                    servicer.startMessaging,
                    request_deserializer=messenger__pb2.MessengerNameRequest.FromString,
                    response_serializer=messenger__pb2.MessengerNameResponse.SerializeToString,
            ),
            'stopMessaging': grpc.unary_unary_rpc_method_handler(
                    servicer.stopMessaging,
                    request_deserializer=messenger__pb2.Empty.FromString,
                    response_serializer=messenger__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Messenger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Messenger(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Messenger/getMessage',
            messenger__pb2.MessengerMessage.SerializeToString,
            messenger__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Messenger/sendMessage',
            messenger__pb2.Empty.SerializeToString,
            messenger__pb2.MessengerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startMessaging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Messenger/startMessaging',
            messenger__pb2.MessengerNameRequest.SerializeToString,
            messenger__pb2.MessengerNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stopMessaging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Messenger/stopMessaging',
            messenger__pb2.Empty.SerializeToString,
            messenger__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
